name: Basic checks

on: [pull_request, push]

jobs:
  npm_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - run: npm ci
        # Runs lint also.  Lint doesn't typecheck.
      - run: npm run build
      - run: npx prettier -c .
